import { createContext, useCallback, useContext, useEffect, useMemo, useState } from "react";
import type { ReactNode } from "react";

export type Idioma = "es" | "ca" | "en";
export const IDIOMAS: Idioma[] = ["es", "ca", "en"];

const CLAU = "portafoli-idioma";

const es = {
  "skip": "Salta al contenido",
  "nav.aria": "Secciones",
  "nav.projects": "Proyectos",
  "nav.contact": "Contacto",
  "lang.aria": "Idioma",
  "sortir": "Salir",
  "doc.title": "Alex Aiguadé Alisultánov · Portafolio",

  "hero.alt": "Retrato de Alex Aiguadé Alisultánov",

  "proj.h": "Proyectos",
  "proj.intro": "{n} aplicaciones que se abren en el navegador. Duermen si nadie entra, así que la primera vez tardan cerca de un minuto.",
  "proj.code": "Código en GitHub",
  "card.try": "Probar la demo",
  "card.shot": "Captura de {t}",
  "car.aria": "Carrusel de proyectos",
  "car.prev": "Proyecto anterior",
  "car.next": "Proyecto siguiente",
  "car.pause": "Parar el carrusel",
  "car.play": "Volver a moverlo",
  "chips.aria": "Tecnologías",
  "chip.qr": "Códigos QR",
  "chip.equip": "Proyecto de equipo",
  "obres.nom": "En obras",
  "obres.why": "Esto todavía está a medias. Mejor no mires debajo de la lona hasta que esté acabado.",
  "feed.loading": "Leyendo los repositorios de GitHub",
  "feed.cache": "GitHub no contesta ahora mismo, así que esta es la última lista guardada.",
  "feed.offline": "GitHub no contesta ahora mismo, así que esta es la lista de siempre, sin la fecha de cada repositorio.",
  "feed.nodesc": "Todavía no tiene descripción en GitHub. El código está publicado y se puede revisar.",
  "feed.code": "Código",
  "feed.soon": "Demo en camino",
  "feed.onlycode": "Solo código por ahora",

  "wake.live.on": "Iniciando {n} demos. Puede tardar cerca de un minuto.",
  "wake.live.on.one": "Iniciando una demo. Puede tardar cerca de un minuto.",
  "wake.live.ready": "{t}: ya contesta, la puedes abrir.",
  "wake.live.fail": "{t}: no ha contestado.",
  "wake.live.done": "Todas las demos contestan.",
  "wake.live.starting": "{t}: arrancando. Puede tardar cerca de un minuto.",
  "estat.fail.why": "Se ha esperado dos minutos y medio sin respuesta. Prueba otra vez.",

  "edu.ev.title": "Máster en Ciberseguridad e Inteligencia Artificial",
  "edu.ls.note": "Nota media 6,313",

  "lg.ru": "Ruso",
  "lg.ru.n": "Lengua materna",
  "lg.es": "Castellano",
  "lg.es.n": "C1",
  "lg.ca": "Catalán",
  "lg.ca.n": "C1",
  "lg.en": "Inglés",
  "lg.en.n": "B1-B2",

  "contact.h": "Contacto",
  "contact.claim": "Hablemos",
  "contact.mail": "Correo",
  "contact.li": "El perfil entero, con más detalle",
  "contact.gh": "Todo el código de los proyectos",
  "foot.made": "Hecho a mano con React y TypeScript",
  "contact.cv": "Ver currículum",

  "cv.back": "Volver al portafolio",
  "cv.download": "Descargar PDF",
  "cv.skip": "Salta al currículum",
  "cv.eyebrow": "Currículum",
  "cv.role": "Técnico de Informática · Sistemas y Ciberseguridad",
  "cv.profile": "Técnico formado en sistemas microinformáticos y desarrollo de aplicaciones, con experiencia real en reparación de equipos y soporte a usuarios. Me apasiona automatizar con inteligencia artificial: uso asistentes de IA y scripts para quitarme tareas repetitivas, montar herramientas propias y resolver incidencias en menos tiempo, y lo estoy ampliando con un máster en Ciberseguridad e IA. Aprendo rápido y me adapto a los cambios. Busco un puesto de técnico de informática donde seguir creciendo y aportar actitud, responsabilidad y energía al equipo.",
  "cv.h.exp": "Experiencia",
  "cv.h.edu": "Formación",
  "cv.h.proj": "Ciberseguridad y proyectos",
  "cv.h.contact": "Contacto",
  "cv.h.tech": "Competencias técnicas",
  "cv.h.lang": "Idiomas",
  "cv.h.soft": "Habilidades",
  "cv.h.other": "Otros datos",
  "cv.e1.t": "Desarrollo de Aplicaciones Multiplataforma (prácticas, 383 h)",
  "cv.e1.b1": "Modelado de personajes y escenarios en 3D con Blender.",
  "cv.e1.b2": "Programación e integración de personajes y escenarios en Unreal Engine.",
  "cv.e2.t": "Técnico de Sistemas Microinformáticos y Redes (prácticas, 370 h)",
  "cv.e2.b1": "Diagnóstico y reparación de equipos informáticos.",
  "cv.e2.b2": "Atención al cliente y soporte a usuarios.",
  "cv.e3.t": "Técnico / Auxiliar de soporte",
  "cv.e4.t": "Dinamizador polideportivo (prácticas)",
  "cv.s1.n": "Abril a diciembre de 2026",
  "cv.s2.t": "CFGS Desarrollo de Aplicaciones Multiplataforma",
  "cv.s2.n": "Perfil Videojuegos y Ocio Digital",
  "cv.s2.b1": "Programación con Java, Spring Boot, JPA, PHP y MySQL.",
  "cv.s2.b2": "Sistemas microinformáticos y redes, diseño web y diseño gráfico.",
  "cv.s3.t": "CFGM Sistemas Microinformáticos y Redes",
  "cv.s3.b1": "Sistemas operativos en entorno gráfico y consola (Windows y Ubuntu).",
  "cv.s3.b2": "Programación con PHP, Python, HTML y CSS. Diseño web.",
  "cv.s4.t": "Curso de Dinamizador Polideportivo (250 h)",
  "cv.p1.t": "Laboratorios de hacking ético",
  "cv.p1.d": "Máquinas resueltas en HackTheBox y TheHackersLabs: explotación web, escalada de privilegios y post-explotación.",
  "cv.p2.t": "Herramientas propias en Kali Linux",
  "cv.p2.d": "Scripts para OSINT, enumeración de subdominios y recolección de evidencias forenses.",
  "cv.apps.h": "Aplicaciones publicadas",
  "cv.apps.aria": "Aplicaciones publicadas, cada una abre su demo",
  "cv.g1": "Sistemas y redes",
  "cv.g2": "Ciberseguridad",
  "cv.g3": "Desarrollo",
  "cv.g4": "Otras herramientas",
  "cv.c.consola": "Consola",
  "cv.c.redes": "Redes",
  "cv.c.soporte": "Soporte técnico",
  "cv.c.forense": "Análisis forense",
  "cv.c.office": "Paquete Office",
  "sk.esc": "Escalada de privilegios",
  "cv.lv.ru": "Nativo · B1 EOI",
  "cv.lv.ca": "C1 · Certificado oficial",
  "cv.lv.en": "B1-B2",
  "cv.k1": "Proactivo",
  "cv.k2": "Responsable",
  "cv.k3": "Orientado al aprendizaje",
  "cv.k4": "Comunicación con usuarios",
  "cv.o1": "Carnet de conducir B",
  "cv.o2": "Mi portafolio",
  "cv.present": "En curso",

  // Rediseno storytelling (plan, seccion 3.6): portada, historia, trayectoria y contacto.
  // Las claves van en el mismo orden en los tres idiomas para poder compararlas.
  "hero.ante": "Técnico de informática",
  "hero.lema": "Reparo y mantengo equipos y redes, programo aplicaciones y ahora me especializo en ciberseguridad.",
  "hero.mov1": "Busco puesto de técnico · Lleida",
  "hero.mov2": "Máster en Ciberseguridad e IA, hasta dic. 2026",
  "hero.cv": "Descargar CV",
  "hero.vercv": "Ver currículum",
  "hero.stack": "Con qué trabajo",
  "stack.win": "Windows y Ubuntu",
  "stack.red": "Redes TCP/IP",
  "hero.pista": "Cómo he llegado hasta aquí",
  // Ficha de la portada: etiqueta, dato y matiz de cada celda (como hero.d1k, d1v y d1n).
  "fitxa.busco": "Busco",
  "fitxa.busco.v": "Puesto de técnico",
  "fitxa.busco.n": "Soporte, sistemas o seguridad",
  "fitxa.on": "Dónde",
  "fitxa.on.v": "Lleida",
  "fitxa.on.n": "Cataluña",
  "fitxa.ara": "Ahora",
  "fitxa.ara.v": "Máster en Ciberseguridad e IA",
  "fitxa.ara.n": "Evolve, hasta diciembre de 2026",
  "fitxa.exp": "Prácticas",
  "fitxa.exp.v": "Soporte y desarrollo",
  "fitxa.exp.n": "Argal e Invelon",
  "copiar": "Copiar",
  "copiat": "Copiado",
  "demos.titol": "Pruébalas ahora",
  "demos.totes": "Ver las {n}",
  "demos.tots": "Ver todos los proyectos",
  "demos.nota": "Duermen si nadie entra. Despertarlas tarda cerca de un minuto.",
  "demos.registre": "Pide crear cuenta",
  "demos.equip": "Equipo",
  "boto.try": "Probar",
  "boto.waking": "Arrancando · {s} s",
  "boto.open": "Abrir la demo",
  "boto.fail": "No contesta, reintentar",
  "nav.story": "Historia",
  "nav.background": "Trayectoria",
  "nav.menu": "Menú",
  "nav.close": "Cerrar",
  "hist.titol": "Protejo lo que antes aprendí a construir.",
  "hist.hw": "Primero, el hardware. Dos años de Sistemas Microinformáticos y Redes. Después, 370 horas de prácticas en Argal diagnosticando y reparando equipos y atendiendo a quien los usaba, y soporte técnico como voluntario en la Fira de Tàrrega.",
  "hist.sw": "Después, el software. En el grado superior de Desarrollo de Aplicaciones Multiplataforma programé con Java, Spring Boot, PHP y MySQL, e hice las prácticas en Invelon Technologies. Hoy tengo {n} aplicaciones publicadas que se abren en el navegador.",
  "hist.seg": "Ahora, la seguridad. Curso el Máster en Ciberseguridad e IA de Evolve hasta diciembre. Resuelvo máquinas en HackTheBox y TheHackersLabs y escribo mis propios scripts en Kali para OSINT, subdominios y evidencias forenses.",
  "hist.fi": "Las tres capas, montadas. Sé cómo va un equipo por dentro, cómo se programa lo que corre encima y por dónde entraría alguien. Eso es lo que llevo a un departamento de IT.",
  "hist.fi.demos": "Ver las demos",
  "hist.fi.mail": "Escríbeme",
  "rail.hw": "Hardware",
  "rail.sw": "Software",
  "rail.seg": "Seguridad",
  "rail.todo": "Montado",
  "rail.skip": "Saltar a los proyectos",
  "rail.aria": "Capítulos",
  "proj.totes": "Despertar todas",
  "proj.compte": "{k} de {n} listas",
  "proj.sol": "Individual",
  "proj.equip": "Equipo de {n}",
  "proj.paper.sol": "Qué hice",
  "proj.paper.equip": "Mi parte",
  "proj.codi": "Código de {t}",
  "tray.h": "Trayectoria",
  "tray.exp": "Experiencia",
  "tray.edu": "Formación",
  "tray.tools": "Herramientas",
  "tray.lang": "Idiomas",
  "tray.now": "En curso",
  "tray.prac": "Prácticas",
  "tray.vol": "Voluntariado",
  "cont.frase": "Si tienes un puesto de técnico o quieres ver algo más a fondo, escríbeme.",
  "cont.pdf": "Descargar CV (PDF)",

  "carrega.err": "No se ha podido cargar la página. Mira la conexión y vuelve a intentarlo.",
  "carrega.retry": "Recargar",

  "porta.eyebrow": "Portafolio",
  "porta.titular": "Técnico de informática · Sistemas · Ciberseguridad",
  "porta.user": "Usuario",
  "porta.pass": "Contraseña",
  "porta.nota": "Entra como invitado, ya está todo puesto.",
  "porta.enter": "Entrar",
  "porta.sending": "Entrando",
  "porta.retry": "Volver a intentarlo",
  "porta.checking": "Comprobando la sesión guardada.",
  "porta.slow": "El servidor estaba dormido y está arrancando. Cerca de un minuto es lo normal.",
  "porta.err.empty": "Escribe el usuario y la contraseña.",
  "porta.err.creds": "El usuario o la contraseña no cuadran.",
  "porta.err.net": "No se ha podido contactar con el servidor. Mira la conexión y vuelve a intentarlo.",
  "porta.err.time": "El servidor no ha contestado a tiempo. Vuelve a intentarlo.",
  "porta.err.server": "El servidor ha contestado con un error. Prueba otra vez dentro de un momento."
};

export type Clau = keyof typeof es;

const ca: Partial<Record<Clau, string>> = {
  "skip": "Salta al contingut",
  "nav.aria": "Seccions",
  "nav.projects": "Projectes",
  "nav.contact": "Contacte",
  "lang.aria": "Idioma",
  "sortir": "Sortir",
  "doc.title": "Alex Aiguadé Alisultánov · Portafoli",

  "hero.alt": "Retrat d'Alex Aiguadé Alisultánov",

  "proj.h": "Projectes",
  "proj.intro": "{n} aplicacions que s'obren al navegador. S'adormen si ningú no hi entra, així que la primera vegada triguen gairebé un minut.",
  "proj.code": "Codi a GitHub",
  "card.try": "Provar la demo",
  "card.shot": "Captura de {t}",
  "car.aria": "Carrusel de projectes",
  "car.prev": "Projecte anterior",
  "car.next": "Projecte següent",
  "car.pause": "Aturar el carrusel",
  "car.play": "Tornar a moure'l",
  "chips.aria": "Tecnologies",
  "chip.qr": "Codis QR",
  "chip.equip": "Projecte d'equip",
  "obres.nom": "En obres",
  "obres.why": "Això encara està a mitges. Val més no mirar sota la lona fins que estigui acabat.",
  "feed.loading": "Llegint els repositoris de GitHub",
  "feed.cache": "GitHub no contesta ara mateix, així que aquesta és l'última llista desada.",
  "feed.offline": "GitHub no contesta ara mateix, així que aquesta és la llista de sempre, sense la data de cada repositori.",
  "feed.nodesc": "Encara no té descripció a GitHub. El codi està publicat i es pot revisar.",
  "feed.code": "Codi",
  "feed.soon": "Demo en camí",
  "feed.onlycode": "Només codi de moment",

  "wake.live.on": "Iniciant {n} demos. Pot trigar prop d'un minut.",
  "wake.live.on.one": "Iniciant una demo. Pot trigar prop d'un minut.",
  "wake.live.ready": "{t}: ja contesta, la pots obrir.",
  "wake.live.fail": "{t}: no ha contestat.",
  "wake.live.done": "Totes les demos contesten.",
  "wake.live.starting": "{t}: arrencant. Pot trigar prop d'un minut.",
  "estat.fail.why": "S'han esperat dos minuts i mig sense resposta. Prova-ho un altre cop.",

  "edu.ev.title": "Màster en Ciberseguretat i Intel·ligència Artificial",
  "edu.ls.note": "Nota mitjana 6,313",

  "lg.ru": "Rus",
  "lg.ru.n": "Llengua materna",
  "lg.es": "Castellà",
  "lg.es.n": "C1",
  "lg.ca": "Català",
  "lg.ca.n": "C1",
  "lg.en": "Anglès",
  "lg.en.n": "B1-B2",

  "contact.h": "Contacte",
  "contact.claim": "Parlem-ne",
  "contact.mail": "Correu",
  "contact.li": "El perfil sencer, amb més detall",
  "contact.gh": "Tot el codi dels projectes",
  "foot.made": "Fet a mà amb React i TypeScript",
  "contact.cv": "Veure el currículum",

  "cv.back": "Tornar al portafoli",
  "cv.download": "Descarrega el PDF",
  "cv.skip": "Salta al currículum",
  "cv.eyebrow": "Currículum",
  "cv.role": "Tècnic d'Informàtica · Sistemes i Ciberseguretat",
  "cv.profile": "Tècnic format en sistemes microinformàtics i desenvolupament d'aplicacions, amb experiència real en reparació d'equips i suport a usuaris. M'apassiona automatitzar amb intel·ligència artificial: faig servir assistents d'IA i scripts per treure'm tasques repetitives, muntar eines pròpies i resoldre incidències en menys temps, i ho estic ampliant amb un màster en Ciberseguretat i IA. Aprenc ràpid i m'adapto als canvis. Busco un lloc de tècnic d'informàtica on seguir creixent i aportar actitud, responsabilitat i energia a l'equip.",
  "cv.h.exp": "Experiència",
  "cv.h.edu": "Formació",
  "cv.h.proj": "Ciberseguretat i projectes",
  "cv.h.contact": "Contacte",
  "cv.h.tech": "Competències tècniques",
  "cv.h.lang": "Idiomes",
  "cv.h.soft": "Habilitats",
  "cv.h.other": "Altres dades",
  "cv.e1.t": "Desenvolupament d'Aplicacions Multiplataforma (pràctiques, 383 h)",
  "cv.e1.b1": "Modelatge de personatges i escenaris en 3D amb Blender.",
  "cv.e1.b2": "Programació i integració de personatges i escenaris a Unreal Engine.",
  "cv.e2.t": "Tècnic de Sistemes Microinformàtics i Xarxes (pràctiques, 370 h)",
  "cv.e2.b1": "Diagnòstic i reparació d'equips informàtics.",
  "cv.e2.b2": "Atenció al client i suport a usuaris.",
  "cv.e3.t": "Tècnic / Auxiliar de suport",
  "cv.e4.t": "Dinamitzador poliesportiu (pràctiques)",
  "cv.s1.n": "Abril a desembre de 2026",
  "cv.s2.t": "CFGS Desenvolupament d'Aplicacions Multiplataforma",
  "cv.s2.n": "Perfil Videojocs i Oci Digital",
  "cv.s2.b1": "Programació amb Java, Spring Boot, JPA, PHP i MySQL.",
  "cv.s2.b2": "Sistemes microinformàtics i xarxes, disseny web i disseny gràfic.",
  "cv.s3.t": "CFGM Sistemes Microinformàtics i Xarxes",
  "cv.s3.b1": "Sistemes operatius en entorn gràfic i consola (Windows i Ubuntu).",
  "cv.s3.b2": "Programació amb PHP, Python, HTML i CSS. Disseny web.",
  "cv.s4.t": "Curs de Dinamitzador Poliesportiu (250 h)",
  "cv.p1.t": "Laboratoris de hacking ètic",
  "cv.p1.d": "Màquines resoltes a HackTheBox i TheHackersLabs: explotació web, escalada de privilegis i post-explotació.",
  "cv.p2.t": "Eines pròpies a Kali Linux",
  "cv.p2.d": "Scripts per a OSINT, enumeració de subdominis i recollida d'evidències forenses.",
  "cv.apps.h": "Aplicacions publicades",
  "cv.apps.aria": "Aplicacions publicades, cadascuna obre la seva demo",
  "cv.g1": "Sistemes i xarxes",
  "cv.g2": "Ciberseguretat",
  "cv.g3": "Desenvolupament",
  "cv.g4": "Altres eines",
  "cv.c.consola": "Consola",
  "cv.c.redes": "Xarxes",
  "cv.c.soporte": "Suport tècnic",
  "cv.c.forense": "Anàlisi forense",
  "cv.c.office": "Paquet Office",
  "sk.esc": "Escalada de privilegis",
  "cv.lv.ru": "Nadiu · B1 EOI",
  "cv.lv.ca": "C1 · Certificat oficial",
  "cv.lv.en": "B1-B2",
  "cv.k1": "Proactiu",
  "cv.k2": "Responsable",
  "cv.k3": "Orientat a l'aprenentatge",
  "cv.k4": "Comunicació amb usuaris",
  "cv.o1": "Carnet de conduir B",
  "cv.o2": "El meu portafoli",
  "cv.present": "En curs",

  "hero.ante": "Tècnic d'informàtica",
  "hero.lema": "Reparo i mantinc equips i xarxes, programo aplicacions i ara m'especialitzo en ciberseguretat.",
  "hero.mov1": "Busco feina de tècnic · Lleida",
  "hero.mov2": "Màster en Ciberseguretat i IA, fins al des. 2026",
  "hero.cv": "Descarregar el CV",
  "hero.vercv": "Veure el currículum",
  "hero.stack": "Amb què treballo",
  "stack.win": "Windows i Ubuntu",
  "stack.red": "Xarxes TCP/IP",
  "hero.pista": "Com he arribat fins aquí",
  "fitxa.busco": "Busco",
  "fitxa.busco.v": "Feina de tècnic",
  "fitxa.busco.n": "Suport, sistemes o seguretat",
  "fitxa.on": "On",
  "fitxa.on.v": "Lleida",
  "fitxa.on.n": "Catalunya",
  "fitxa.ara": "Ara",
  "fitxa.ara.v": "Màster en Ciberseguretat i IA",
  "fitxa.ara.n": "Evolve, fins al desembre de 2026",
  "fitxa.exp": "Pràctiques",
  "fitxa.exp.v": "Suport i desenvolupament",
  "fitxa.exp.n": "Argal i Invelon",
  "copiar": "Copiar",
  "copiat": "Copiat",
  "demos.titol": "Prova-les ara",
  "demos.totes": "Veure-les totes ({n})",
  "demos.tots": "Veure tots els projectes",
  "demos.nota": "S'adormen si ningú no hi entra. Despertar-les triga gairebé un minut.",
  "demos.registre": "Demana crear un compte",
  "demos.equip": "Equip",
  "boto.try": "Provar",
  "boto.waking": "Arrencant · {s} s",
  "boto.open": "Obrir la demo",
  "boto.fail": "No respon, torna-ho a provar",
  "nav.story": "Història",
  "nav.background": "Trajectòria",
  "nav.menu": "Menú",
  "nav.close": "Tancar",
  "hist.titol": "Protegeixo el que abans vaig aprendre a construir.",
  "hist.hw": "Primer, el maquinari. Dos anys de Sistemes Microinformàtics i Xarxes. Després, 370 hores de pràctiques a Argal diagnosticant i reparant equips i atenent qui els feia servir, i suport tècnic com a voluntari a la Fira de Tàrrega.",
  "hist.sw": "Després, el programari. Al grau superior de Desenvolupament d'Aplicacions Multiplataforma vaig programar amb Java, Spring Boot, PHP i MySQL, i vaig fer les pràctiques a Invelon Technologies. Avui tinc {n} aplicacions publicades que s'obren al navegador.",
  "hist.seg": "Ara, la seguretat. Curso el Màster en Ciberseguretat i IA d'Evolve fins al desembre. Resolc màquines a HackTheBox i TheHackersLabs i escric els meus propis scripts a Kali per a OSINT, subdominis i evidències forenses.",
  "hist.fi": "Les tres capes, muntades. Sé com funciona un equip per dins, com es programa el que hi corre i per on hi entraria algú. Això és el que porto a un departament d'IT.",
  "hist.fi.demos": "Veure les demos",
  "hist.fi.mail": "Escriu-me",
  "rail.hw": "Maquinari",
  "rail.sw": "Programari",
  "rail.seg": "Seguretat",
  "rail.todo": "Muntat",
  "rail.skip": "Salta als projectes",
  "rail.aria": "Capítols",
  "proj.totes": "Desperta-les totes",
  "proj.compte": "{k} de {n} a punt",
  "proj.sol": "Individual",
  "proj.equip": "Equip de {n}",
  "proj.paper.sol": "Què vaig fer",
  "proj.paper.equip": "La meva part",
  "proj.codi": "Codi de {t}",
  "tray.h": "Trajectòria",
  "tray.exp": "Experiència",
  "tray.edu": "Formació",
  "tray.tools": "Eines",
  "tray.lang": "Idiomes",
  "tray.now": "En curs",
  "tray.prac": "Pràctiques",
  "tray.vol": "Voluntariat",
  "cont.frase": "Si tens una feina de tècnic o vols veure alguna cosa més a fons, escriu-me.",
  "cont.pdf": "Descarregar el CV (PDF)",

  "carrega.err": "No s'ha pogut carregar la pàgina. Mira la connexió i torna-ho a provar.",
  "carrega.retry": "Recarregar",

  "porta.eyebrow": "Portafoli",
  "porta.titular": "Tècnic d'informàtica · Sistemes · Ciberseguretat",
  "porta.user": "Usuari",
  "porta.pass": "Contrasenya",
  "porta.nota": "Entra com a convidat, ja ho tens tot posat.",
  "porta.enter": "Entrar",
  "porta.sending": "Entrant",
  "porta.retry": "Tornar-ho a provar",
  "porta.checking": "Comprovant la sessió desada.",
  "porta.slow": "El servidor estava adormit i s'està engegant. Prop d'un minut és el normal.",
  "porta.err.empty": "Escriu l'usuari i la contrasenya.",
  "porta.err.creds": "L'usuari o la contrasenya no quadren.",
  "porta.err.net": "No s'ha pogut contactar amb el servidor. Mira la connexió i torna-ho a provar.",
  "porta.err.time": "El servidor no ha contestat a temps. Torna-ho a provar.",
  "porta.err.server": "El servidor ha contestat amb un error. Prova-ho un altre cop d'aquí a un moment."
};

const en: Partial<Record<Clau, string>> = {
  "skip": "Skip to content",
  "nav.aria": "Sections",
  "nav.projects": "Projects",
  "nav.contact": "Contact",
  "lang.aria": "Language",
  "sortir": "Sign out",
  "doc.title": "Alex Aiguadé Alisultánov · Portfolio",

  "hero.alt": "Portrait of Alex Aiguadé Alisultánov",

  "proj.h": "Projects",
  "proj.intro": "{n} apps that open in the browser. They sleep when nobody visits, so the first time they take about a minute.",
  "proj.code": "Code on GitHub",
  "card.try": "Try the demo",
  "card.shot": "Screenshot of {t}",
  "car.aria": "Project carousel",
  "car.prev": "Previous project",
  "car.next": "Next project",
  "car.pause": "Pause the carousel",
  "car.play": "Start it again",
  "chips.aria": "Technologies",
  "chip.qr": "QR codes",
  "chip.equip": "Team project",
  "obres.nom": "Under construction",
  "obres.why": "This one is still halfway there. Better not to peek under the tarp until it is finished.",
  "feed.loading": "Reading the repositories from GitHub",
  "feed.cache": "GitHub is not answering right now, so this is the last list that was saved.",
  "feed.offline": "GitHub is not answering right now, so this is the usual list, without the date of each repository.",
  "feed.nodesc": "No description on GitHub yet. The code is published and you can go through it.",
  "feed.code": "Code",
  "feed.soon": "Demo on the way",
  "feed.onlycode": "Code only for now",

  "wake.live.on": "Starting {n} demos. It can take close to a minute.",
  "wake.live.on.one": "Starting one demo. It can take close to a minute.",
  "wake.live.ready": "{t}: answering now, you can open it.",
  "wake.live.fail": "{t}: no answer.",
  "wake.live.done": "Every demo answers.",
  "wake.live.starting": "{t}: starting up. It can take close to a minute.",
  "estat.fail.why": "Two and a half minutes went by with no answer. Give it another go.",

  "edu.ev.title": "Master's in Cybersecurity and Artificial Intelligence",
  "edu.ls.note": "Average grade 6.313",

  "lg.ru": "Russian",
  "lg.ru.n": "Mother tongue",
  "lg.es": "Spanish",
  "lg.es.n": "C1",
  "lg.ca": "Catalan",
  "lg.ca.n": "C1",
  "lg.en": "English",
  "lg.en.n": "B1-B2",

  "contact.h": "Contact",
  "contact.claim": "Let's talk",
  "contact.mail": "Email",
  "contact.li": "The full profile, in more detail",
  "contact.gh": "All the code from the projects",
  "foot.made": "Handmade with React and TypeScript",
  "contact.cv": "View CV",

  "cv.back": "Back to portfolio",
  "cv.download": "Download PDF",
  "cv.skip": "Skip to the CV",
  "cv.eyebrow": "Curriculum vitae",
  "cv.role": "IT Technician · Systems and Cybersecurity",
  "cv.profile": "Technician trained in microcomputer systems and application development, with real experience in equipment repair and user support. I love automating with artificial intelligence: I use AI assistants and scripts to get rid of repetitive tasks, build my own tools and solve incidents in less time, and I am taking it further with a Master's in Cybersecurity and AI. I learn fast and adapt to change. I'm looking for an IT technician position where I can keep growing and bring attitude, responsibility and energy to the team.",
  "cv.h.exp": "Experience",
  "cv.h.edu": "Education",
  "cv.h.proj": "Cybersecurity and projects",
  "cv.h.contact": "Contact",
  "cv.h.tech": "Technical skills",
  "cv.h.lang": "Languages",
  "cv.h.soft": "Strengths",
  "cv.h.other": "Other details",
  "cv.e1.t": "Cross-platform Application Development (internship, 383 h)",
  "cv.e1.b1": "3D modelling of characters and scenes with Blender.",
  "cv.e1.b2": "Programming and integrating characters and scenes in Unreal Engine.",
  "cv.e2.t": "Microcomputer Systems and Networks Technician (internship, 370 h)",
  "cv.e2.b1": "Diagnosing and repairing computer equipment.",
  "cv.e2.b2": "Customer service and user support.",
  "cv.e3.t": "Technician / Support assistant",
  "cv.e4.t": "Sports centre activity leader (internship)",
  "cv.s1.n": "April to December 2026",
  "cv.s2.t": "Advanced vocational degree in Cross-platform Application Development",
  "cv.s2.n": "Video Games and Digital Entertainment track",
  "cv.s2.b1": "Programming with Java, Spring Boot, JPA, PHP and MySQL.",
  "cv.s2.b2": "Microcomputer systems and networks, web design and graphic design.",
  "cv.s3.t": "Intermediate vocational degree in Microcomputer Systems and Networks",
  "cv.s3.b1": "Operating systems in graphical and command-line environments (Windows and Ubuntu).",
  "cv.s3.b2": "Programming with PHP, Python, HTML and CSS. Web design.",
  "cv.s4.t": "Sports Centre Activity Leader course (250 h)",
  "cv.p1.t": "Ethical hacking labs",
  "cv.p1.d": "Machines solved on HackTheBox and TheHackersLabs: web exploitation, privilege escalation and post-exploitation.",
  "cv.p2.t": "Own tools on Kali Linux",
  "cv.p2.d": "Scripts for OSINT, subdomain enumeration and forensic evidence collection.",
  "cv.apps.h": "Published applications",
  "cv.apps.aria": "Published applications, each one opens its demo",
  "cv.g1": "Systems and networks",
  "cv.g2": "Cybersecurity",
  "cv.g3": "Development",
  "cv.g4": "Other tools",
  "cv.c.consola": "Command line",
  "cv.c.redes": "Networking",
  "cv.c.soporte": "Technical support",
  "cv.c.forense": "Forensics",
  "cv.c.office": "Office suite",
  "sk.esc": "Privilege escalation",
  "cv.lv.ru": "Native · B1 EOI",
  "cv.lv.ca": "C1 · Official certificate",
  "cv.lv.en": "B1-B2",
  "cv.k1": "Proactive",
  "cv.k2": "Responsible",
  "cv.k3": "Learning-oriented",
  "cv.k4": "Communication with users",
  "cv.o1": "Category B driving licence",
  "cv.o2": "My portfolio",
  "cv.present": "In progress",

  "hero.ante": "IT technician",
  "hero.lema": "I fix and maintain computers and networks, I build applications, and now I'm specialising in cybersecurity.",
  "hero.mov1": "Looking for an IT role · Lleida",
  "hero.mov2": "Master's in Cybersecurity and AI, until Dec 2026",
  "hero.cv": "Download CV",
  "hero.vercv": "View CV",
  "hero.stack": "What I work with",
  "stack.win": "Windows and Ubuntu",
  "stack.red": "TCP/IP networking",
  "hero.pista": "How I got here",
  "fitxa.busco": "Looking for",
  "fitxa.busco.v": "An IT technician role",
  "fitxa.busco.n": "Support, systems or security",
  "fitxa.on": "Based in",
  "fitxa.on.v": "Lleida",
  "fitxa.on.n": "Catalonia, Spain",
  "fitxa.ara": "Now",
  "fitxa.ara.v": "Master's in Cybersecurity and AI",
  "fitxa.ara.n": "Evolve, until December 2026",
  "fitxa.exp": "Internships",
  "fitxa.exp.v": "Support and development",
  "fitxa.exp.n": "Argal and Invelon",
  "copiar": "Copy",
  "copiat": "Copied",
  "demos.titol": "Try them now",
  "demos.totes": "See all {n}",
  "demos.tots": "See all projects",
  "demos.nota": "They sleep when nobody visits. Waking them takes about a minute.",
  "demos.registre": "Asks you to sign up",
  "demos.equip": "Team",
  "boto.try": "Try it",
  "boto.waking": "Starting · {s} s",
  "boto.open": "Open the demo",
  "boto.fail": "No answer, try again",
  "nav.story": "Story",
  "nav.background": "Background",
  "nav.menu": "Menu",
  "nav.close": "Close",
  "hist.titol": "I protect what I first learned to build.",
  "hist.hw": "Hardware first. Two years of Computer Systems and Networks. Then a 370-hour internship at Argal diagnosing and repairing computers and helping the people who used them, plus tech support as a volunteer at Fira de Tàrrega.",
  "hist.sw": "Then, software. In the Multiplatform Application Development diploma I wrote Java, Spring Boot, PHP and MySQL, and did my placement at Invelon Technologies. Today I have {n} published apps you can open in the browser.",
  "hist.seg": "Now, security. I'm doing the Master's in Cybersecurity and AI at Evolve until December. I solve machines on HackTheBox and TheHackersLabs and write my own Kali scripts for OSINT, subdomains and forensic evidence.",
  "hist.fi": "All three layers, assembled. I know how a computer works inside, how to program what runs on it and where someone would try to get in. That's what I bring to an IT team.",
  "hist.fi.demos": "See the demos",
  "hist.fi.mail": "Email me",
  "rail.hw": "Hardware",
  "rail.sw": "Software",
  "rail.seg": "Security",
  "rail.todo": "Assembled",
  "rail.skip": "Skip to the projects",
  "rail.aria": "Chapters",
  "proj.totes": "Wake them all",
  "proj.compte": "{k} of {n} ready",
  "proj.sol": "Solo project",
  "proj.equip": "Team of {n}",
  "proj.paper.sol": "What I did",
  "proj.paper.equip": "My part",
  "proj.codi": "Code for {t}",
  "tray.h": "Background",
  "tray.exp": "Experience",
  "tray.edu": "Education",
  "tray.tools": "Tools",
  "tray.lang": "Languages",
  "tray.now": "In progress",
  "tray.prac": "Internship",
  "tray.vol": "Volunteering",
  "cont.frase": "If you have an IT technician role or want to look at something in more depth, write to me.",
  "cont.pdf": "Download CV (PDF)",

  "carrega.err": "The page could not load. Check your connection and try again.",
  "carrega.retry": "Reload",

  "porta.eyebrow": "Portfolio",
  "porta.titular": "IT technician · Systems · Cybersecurity",
  "porta.user": "Username",
  "porta.pass": "Password",
  "porta.nota": "Come in as a guest, everything is already filled in.",
  "porta.enter": "Sign in",
  "porta.sending": "Signing in",
  "porta.retry": "Try again",
  "porta.checking": "Checking the saved session.",
  "porta.slow": "The server was asleep and is starting up. Close to a minute is normal.",
  "porta.err.empty": "Type the username and the password.",
  "porta.err.creds": "That username and password do not match.",
  "porta.err.net": "Could not reach the server. Check your connection and try again.",
  "porta.err.time": "The server did not answer in time. Try again.",
  "porta.err.server": "The server answered with an error. Give it another go in a moment."
};

const DICCIONARIS: Record<Idioma, Partial<Record<Clau, string>>> = { es, ca, en };

/** Texto en el idioma pedido. Si falta una frase se cae al castellano, nunca a la clave. */
export function traduir(idioma: Idioma, clau: Clau): string {
  return DICCIONARIS[idioma][clau] ?? es[clau] ?? "";
}

type Context = {
  idioma: Idioma;
  t: (clau: Clau, valors?: Record<string, string | number>) => string;
  canviar: (idioma: Idioma) => void;
};

const IdiomaContext = createContext<Context | null>(null);

function recordat(): Idioma {
  try {
    const desat = window.localStorage.getItem(CLAU);
    if (desat === "ca" || desat === "en" || desat === "es") return desat;
  } catch {
    // Ventana privada o almacenamiento bloqueado: se arranca en castellano.
  }
  return "es";
}

export function ProveidorIdioma({ children }: { children: ReactNode }) {
  const [idioma, setIdioma] = useState<Idioma>(recordat);

  useEffect(() => {
    document.documentElement.lang = idioma;
    document.title = traduir(idioma, "doc.title");
  }, [idioma]);

  const canviar = useCallback((nou: Idioma) => {
    setIdioma(nou);
    try {
      window.localStorage.setItem(CLAU, nou);
    } catch {
      // La eleccion dura lo que la visita.
    }
  }, []);

  const t = useCallback(
    (clau: Clau, valors?: Record<string, string | number>) => {
      let text = traduir(idioma, clau);
      if (valors) {
        for (const nom of Object.keys(valors)) {
          text = text.split("{" + nom + "}").join(String(valors[nom]));
        }
      }
      return text;
    },
    [idioma]
  );

  const valor = useMemo(() => ({ idioma, t, canviar }), [idioma, t, canviar]);
  return <IdiomaContext value={valor}>{children}</IdiomaContext>;
}

export function useIdioma(): Context {
  const valor = useContext(IdiomaContext);
  if (!valor) throw new Error("useIdioma necesita estar dentro de ProveidorIdioma");
  return valor;
}
