import { createContext, useCallback, useContext, useEffect, useMemo, useState } from "react";
import type { ReactNode } from "react";

export type Idioma = "es" | "ca" | "en";
export const IDIOMAS: Idioma[] = ["es", "ca", "en"];

const CLAU = "portafoli-idioma";

const es = {
  "skip": "Salta al contenido",
  "nav.aria": "Secciones",
  "nav.about": "Sobre mí",
  "nav.projects": "Proyectos",
  "nav.edu": "Formación",
  "nav.skills": "Aptitudes",
  "nav.contact": "Contacto",
  "lang.aria": "Idioma",
  "sortir": "Salir",
  "doc.title": "Alex Aiguadé Alisultánov · Portafolio",

  "hero.eyebrow": "Técnico IT · Sistemas · Ciberseguridad",
  "hero.lead": "Técnico IT centrado en sistemas y ciberseguridad, con base en desarrollo de aplicaciones. Ahora curso el Máster en Ciberseguridad e IA. Busco incorporarme al departamento de IT de una empresa del sector.",
  "hero.cta": "Mira los proyectos",
  "hero.alt": "Retrato de Alex Aiguadé Alisultánov",
  "hero.d1k": "Ahora mismo",
  "hero.d1v": "Máster en Ciberseguridad e IA",
  "hero.d1n": "Evolve, en curso",
  "hero.d2k": "Base",
  "hero.d2v": "Desarrollo de Aplicaciones",
  "hero.d2n": "Grado superior, 2024",
  "hero.d3k": "Proyectos publicados",
  "hero.d3n": "Código abierto en GitHub",
  "hero.d4k": "Dónde",
  "hero.d4v": "Anglesola, Cataluña",
  "hero.d4n": "España",

  "about.h": "Sobre mí",
  "about.claim": "Protejo lo que antes aprendí a construir.",
  "about.p1": "Soy Técnico Superior en Desarrollo de Aplicaciones y ahora curso el Máster en Ciberseguridad e Inteligencia Artificial de Evolve. La base la traigo de la programación; lo que trabajo ahora es la protección de activos digitales y el uso de la IA para optimizar y asegurar procesos.",
  "about.p2": "Busco incorporarme al departamento de IT de una compañía del sector de la ciberseguridad, donde pueda aportar en la gestión de infraestructura, la automatización de tareas y el desarrollo de soluciones seguras. Tengo un inglés intermedio (B1-B2), suficiente para moverme en entornos técnicos.",
  "about.p3": "Lo que más me interesa: el desarrollo e integración de software seguro, la ciberseguridad operativa y la gestión de sistemas IT, la IA aplicada a entornos tecnológicos y automatizar lo que se repite. Los proyectos de aquí abajo son de desarrollo web, de la etapa del ciclo superior, y siguen explicando cómo trabajo.",

  "proj.h": "Proyectos",
  "proj.intro": "Cada tarjeta lleva las tecnologías con las que está hecho el proyecto y, si ya está desplegado, el enlace para probarlo.",
  "proj.code": "Código en GitHub",
  "chips.aria": "Tecnologías",
  "chip.qr": "Códigos QR",
  "chip.equip": "Proyecto de equipo",
  "obres.nom": "En obras",
  "obres.why": "Esto todavía está a medias. Mejor no mires debajo de la lona hasta que esté acabado.",
  "feed.loading": "Leyendo los repositorios de GitHub",
  "feed.cache": "GitHub no contesta ahora mismo, así que esta es la última lista guardada.",
  "feed.offline": "GitHub no contesta ahora mismo, así que esta es la lista de siempre, sin la fecha de cada repositorio.",
  "feed.nodesc": "Todavía no tiene descripción en GitHub. El código está publicado y se puede revisar.",
  "feed.updated": "Actualizado {t}",
  "feed.try": "Probar la app",
  "feed.code": "Código",
  "feed.soon": "Demo en camino",
  "feed.onlycode": "Solo código por ahora",

  "wake.title": "Las demos se duermen solas",
  "wake.text": "Están en un plan gratuito que las apaga a los quince minutos sin visitas. Arráncalas todas de una vez, o una a una desde su tarjeta, y cada una te va diciendo cómo está. Desde aquí solo se puede saber si el servidor contesta, no qué contesta.",
  "wake.on": "Iniciar las {n} demos",
  "wake.on.one": "Iniciar la demo",
  "wake.working": "Quedan {n} por contestar",
  "wake.working.one": "Queda 1 por contestar",
  "wake.retry": "Volver a intentarlo con {n}",
  "wake.retry.one": "Volver a intentarlo",
  "wake.done": "Las demos ya están en marcha",
  "wake.hint": "La primera arrancada tarda cerca de un minuto. Puedes seguir leyendo mientras.",
  "wake.hint.working": "Cerca de un minuto es lo normal. Llevan {s} s.",
  "wake.hint.done": "Se quedan despiertas mientras las uses. A los quince minutos sin visitas vuelven a dormirse.",
  "wake.hint.some": "Alguna no ha contestado a tiempo. Puedes volver a intentarlo desde su tarjeta o desde aquí.",
  "wake.live.on": "Iniciando {n} demos. Puede tardar cerca de un minuto.",
  "wake.live.on.one": "Iniciando una demo. Puede tardar cerca de un minuto.",
  "wake.live.ready": "{t}: ya contesta, la puedes abrir.",
  "wake.live.fail": "{t}: no ha contestado.",
  "wake.live.done": "Todas las demos contestan.",
  "wake.live.starting": "{t}: arrancando. Puede tardar cerca de un minuto.",
  "demo.start": "Iniciar la demo",
  "estat.off": "Sin comprobar",
  "estat.off.why": "Iníciala para poder abrirla.",
  "estat.waking": "Arrancando",
  "estat.waking.why": "El servidor está arrancando. Suele tardar cerca de un minuto.",
  "estat.on": "Activa",
  "estat.on.why": "Ya contesta, puedes abrirla.",
  "estat.fail": "No ha contestado",
  "estat.fail.why": "Se ha esperado dos minutos y medio sin respuesta. Prueba otra vez.",
  "estat.secs": "{s} s",
  "estat.again": "Volver a intentarlo",

  "edu.h": "Formación",
  "edu.intro": "De dónde vienen la base de desarrollo y la especialización en seguridad.",
  "edu.aria": "Contenidos",
  "edu.ev.when": "Abril de 2026 a diciembre de 2026",
  "edu.ev.tag": "En curso",
  "edu.ev.title": "Máster en Ciberseguridad e Inteligencia Artificial",
  "edu.ev.c1": "Hacking ético y metodología de auditoría",
  "edu.ev.c2": "Reconocimiento pasivo y activo",
  "edu.ev.c3": "OSINT y footprinting",
  "edu.ev.c4": "Protocolos de red, segmentación y arquitecturas de comunicación",
  "edu.ev.c5": "Explotación de vulnerabilidades",
  "edu.ev.c7": "Pivoting, movimiento lateral y escalada de privilegios",
  "edu.ev.c8": "Normativa, cumplimiento y marco legal",
  "edu.ev.c9": "Pentesting avanzado en entornos reales",
  "edu.ev.c11": "Blue Team, SOC y respuesta ante incidentes",
  "edu.ls.when": "Septiembre de 2022 a mayo de 2024",
  "edu.ls.title": "Ciclo Formativo de Grado Superior en Desarrollo de Aplicaciones",
  "edu.ls.note": "Nota media 6,313",
  "edu.gm.when": "2020 a 2022",
  "edu.gm.title": "Ciclo Formativo de Grado Medio en Sistemas Microinformáticos y Redes",

  "skills.h": "Aptitudes",
  "skills.intro": "Agrupadas por familia, para que se vea de un vistazo de qué va cada parte.",
  "skills.g1": "Pentesting y ofensiva",
  "skills.g2": "Defensa",
  "skills.g3": "Metodologías y normativa",
  "skills.g4": "Programación y datos",
  "skills.g5": "Inteligencia artificial",
  "skills.g6": "Aptitudes personales",
  "skills.g7": "Idiomas",
  "sk.explo": "Explotación de vulnerabilidades",
  "sk.esc": "Escalada de privilegios",
  "sk.lat": "Movimiento lateral y pivoting",
  "sk.post": "Post-explotación",
  "sk.wifi": "Auditoría Wi-Fi y móvil",
  "sk.e2e": "Auditoría end-to-end",
  "sk.info": "Informe ejecutivo",
  "sk.inc": "Respuesta ante incidentes",
  "sk.cve": "CVE y NVD",
  "sk.rgpd": "RGPD",
  "sk.ag": "Agentes con Python",
  "sk.ml": "Aprendizaje automático",
  "sk.llm": "Modelos de lenguaje",
  "sk.iacyber": "IA aplicada a la ciberseguridad",
  "skills.soft": "De la etapa en La Salle Mollerussa: trabajo en equipo, resolución de problemas, responsabilidad, facilidad de adaptación, escucha activa, proactividad, empatía, respeto y tolerancia.",
  "lg.ru": "Ruso",
  "lg.ru.n": "Lengua materna",
  "lg.es": "Castellano",
  "lg.es.n": "C1",
  "lg.ca": "Catalán",
  "lg.ca.n": "C1",
  "lg.en": "Inglés",
  "lg.en.n": "B1-B2",

  "contact.h": "Contacto",
  "contact.claim": "Hablemos",
  "contact.intro": "Si te encaja mi perfil, escríbeme por donde te vaya mejor. Contesto enseguida.",
  "contact.mail": "Correo",
  "contact.li": "El perfil entero, con más detalle",
  "contact.gh": "Todo el código de los proyectos",
  "foot.made": "Hecho a mano con React y TypeScript",

  "porta.eyebrow": "Portafolio",
  "porta.titular": "Técnico IT · Sistemas · Ciberseguridad",
  "porta.user": "Usuario",
  "porta.pass": "Contraseña",
  "porta.nota": "Entra como invitado, ya está todo puesto.",
  "porta.enter": "Entrar",
  "porta.sending": "Entrando",
  "porta.retry": "Volver a intentarlo",
  "porta.checking": "Comprobando la sesión guardada.",
  "porta.slow": "El servidor estaba dormido y está arrancando. Cerca de un minuto es lo normal.",
  "porta.err.empty": "Escribe el usuario y la contraseña.",
  "porta.err.creds": "El usuario o la contraseña no cuadran.",
  "porta.err.net": "No se ha podido contactar con el servidor. Mira la conexión y vuelve a intentarlo.",
  "porta.err.time": "El servidor no ha contestado a tiempo. Vuelve a intentarlo.",
  "porta.err.server": "El servidor ha contestado con un error. Prueba otra vez dentro de un momento."
};

export type Clau = keyof typeof es;

const ca: Partial<Record<Clau, string>> = {
  "skip": "Salta al contingut",
  "nav.aria": "Seccions",
  "nav.about": "Sobre mi",
  "nav.projects": "Projectes",
  "nav.edu": "Formació",
  "nav.skills": "Aptituds",
  "nav.contact": "Contacte",
  "lang.aria": "Idioma",
  "sortir": "Sortir",
  "doc.title": "Alex Aiguadé Alisultánov · Portafoli",

  "hero.eyebrow": "Tècnic IT · Sistemes · Ciberseguretat",
  "hero.lead": "Tècnic IT centrat en sistemes i ciberseguretat, amb base en desenvolupament d'aplicacions. Ara curso el Màster en Ciberseguretat i IA. Busco incorporar-me al departament d'IT d'una empresa del sector.",
  "hero.cta": "Mira els projectes",
  "hero.alt": "Retrat d'Alex Aiguadé Alisultánov",
  "hero.d1k": "Ara mateix",
  "hero.d1v": "Màster en Ciberseguretat i IA",
  "hero.d1n": "Evolve, en curs",
  "hero.d2k": "Base",
  "hero.d2v": "Desenvolupament d'Aplicacions",
  "hero.d2n": "Grau superior, 2024",
  "hero.d3k": "Projectes publicats",
  "hero.d3n": "Codi obert a GitHub",
  "hero.d4k": "On",
  "hero.d4v": "Anglesola, Catalunya",
  "hero.d4n": "Espanya",

  "about.h": "Sobre mi",
  "about.claim": "Protegeixo el que abans vaig aprendre a construir.",
  "about.p1": "Sóc Tècnic Superior en Desenvolupament d'Aplicacions i ara curso el Màster en Ciberseguretat i Intel·ligència Artificial d'Evolve. La base la porto de la programació; el que treballo ara és la protecció d'actius digitals i l'ús de la IA per optimitzar i assegurar processos.",
  "about.p2": "Busco incorporar-me al departament d'IT d'una companyia del sector de la ciberseguretat, on pugui aportar en la gestió d'infraestructura, l'automatització de tasques i el desenvolupament de solucions segures. Tinc un anglès intermedi (B1-B2), prou per moure'm en entorns tècnics.",
  "about.p3": "El que més m'interessa: el desenvolupament i la integració de programari segur, la ciberseguretat operativa i la gestió de sistemes IT, la IA aplicada a entorns tecnològics i automatitzar el que es repeteix. Els projectes d'aquí sota són de desenvolupament web, de l'etapa del cicle superior, i segueixen explicant com treballo.",

  "proj.h": "Projectes",
  "proj.intro": "Cada targeta porta les tecnologies amb què està fet el projecte i, si ja està desplegat, l'enllaç per provar-lo.",
  "proj.code": "Codi a GitHub",
  "chips.aria": "Tecnologies",
  "chip.qr": "Codis QR",
  "chip.equip": "Projecte d'equip",
  "obres.nom": "En obres",
  "obres.why": "Això encara està a mitges. Val més no mirar sota la lona fins que estigui acabat.",
  "feed.loading": "Llegint els repositoris de GitHub",
  "feed.cache": "GitHub no contesta ara mateix, així que aquesta és l'última llista desada.",
  "feed.offline": "GitHub no contesta ara mateix, així que aquesta és la llista de sempre, sense la data de cada repositori.",
  "feed.nodesc": "Encara no té descripció a GitHub. El codi està publicat i es pot revisar.",
  "feed.updated": "Actualitzat {t}",
  "feed.try": "Provar l'aplicació",
  "feed.code": "Codi",
  "feed.soon": "Demo en camí",
  "feed.onlycode": "Només codi de moment",

  "wake.title": "Les demos s'adormen soles",
  "wake.text": "Són en un pla gratuït que les apaga als quinze minuts sense visites. Arrenca-les totes de cop, o una a una des de la seva targeta, i cadascuna et va dient com està. Des d'aquí només es pot saber si el servidor contesta, no pas què contesta.",
  "wake.on": "Iniciar les {n} demos",
  "wake.on.one": "Iniciar la demo",
  "wake.working": "En queden {n} per contestar",
  "wake.working.one": "En queda 1 per contestar",
  "wake.retry": "Tornar-ho a provar amb {n}",
  "wake.retry.one": "Tornar-ho a provar",
  "wake.done": "Les demos ja són en marxa",
  "wake.hint": "La primera arrencada triga prop d'un minut. Pots seguir llegint mentrestant.",
  "wake.hint.working": "Prop d'un minut és el normal. Porten {s} s.",
  "wake.hint.done": "Es queden despertes mentre les facis servir. Als quinze minuts sense visites tornen a adormir-se.",
  "wake.hint.some": "Alguna no ha contestat a temps. Pots tornar-ho a provar des de la seva targeta o des d'aquí.",
  "wake.live.on": "Iniciant {n} demos. Pot trigar prop d'un minut.",
  "wake.live.on.one": "Iniciant una demo. Pot trigar prop d'un minut.",
  "wake.live.ready": "{t}: ja contesta, la pots obrir.",
  "wake.live.fail": "{t}: no ha contestat.",
  "wake.live.done": "Totes les demos contesten.",
  "wake.live.starting": "{t}: arrencant. Pot trigar prop d'un minut.",
  "demo.start": "Iniciar la demo",
  "estat.off": "Sense comprovar",
  "estat.off.why": "Inicia-la per poder obrir-la.",
  "estat.waking": "Arrencant",
  "estat.waking.why": "El servidor està arrencant. Sol trigar prop d'un minut.",
  "estat.on": "Activa",
  "estat.on.why": "Ja contesta, la pots obrir.",
  "estat.fail": "No ha contestat",
  "estat.fail.why": "S'han esperat dos minuts i mig sense resposta. Prova-ho un altre cop.",
  "estat.secs": "{s} s",
  "estat.again": "Tornar-ho a provar",

  "edu.h": "Formació",
  "edu.intro": "D'on venen la base de desenvolupament i l'especialització en seguretat.",
  "edu.aria": "Continguts",
  "edu.ev.when": "Abril de 2026 a desembre de 2026",
  "edu.ev.tag": "En curs",
  "edu.ev.title": "Màster en Ciberseguretat i Intel·ligència Artificial",
  "edu.ev.c1": "Hacking ètic i metodologia d'auditoria",
  "edu.ev.c2": "Reconeixement passiu i actiu",
  "edu.ev.c3": "OSINT i footprinting",
  "edu.ev.c4": "Protocols de xarxa, segmentació i arquitectures de comunicació",
  "edu.ev.c5": "Explotació de vulnerabilitats",
  "edu.ev.c7": "Pivoting, moviment lateral i escalada de privilegis",
  "edu.ev.c8": "Normativa, compliment i marc legal",
  "edu.ev.c9": "Pentesting avançat en entorns reals",
  "edu.ev.c11": "Blue Team, SOC i resposta davant incidents",
  "edu.ls.when": "Setembre de 2022 a maig de 2024",
  "edu.ls.title": "Cicle Formatiu de Grau Superior en Desenvolupament d'Aplicacions",
  "edu.ls.note": "Nota mitjana 6,313",
  "edu.gm.when": "2020 a 2022",
  "edu.gm.title": "Cicle Formatiu de Grau Mitjà en Sistemes Microinformàtics i Xarxes",

  "skills.h": "Aptituds",
  "skills.intro": "Agrupades per família, perquè es vegi d'un cop d'ull de què va cada part.",
  "skills.g1": "Pentesting i ofensiva",
  "skills.g2": "Defensa",
  "skills.g3": "Metodologies i normativa",
  "skills.g4": "Programació i dades",
  "skills.g5": "Intel·ligència artificial",
  "skills.g6": "Aptituds personals",
  "skills.g7": "Idiomes",
  "sk.explo": "Explotació de vulnerabilitats",
  "sk.esc": "Escalada de privilegis",
  "sk.lat": "Moviment lateral i pivoting",
  "sk.post": "Post-explotació",
  "sk.wifi": "Auditoria Wi-Fi i mòbil",
  "sk.e2e": "Auditoria end-to-end",
  "sk.info": "Informe executiu",
  "sk.inc": "Resposta davant incidents",
  "sk.cve": "CVE i NVD",
  "sk.rgpd": "RGPD",
  "sk.ag": "Agents amb Python",
  "sk.ml": "Aprenentatge automàtic",
  "sk.llm": "Models de llenguatge",
  "sk.iacyber": "IA aplicada a la ciberseguretat",
  "skills.soft": "De l'etapa a La Salle Mollerussa: treball en equip, resolució de problemes, responsabilitat, facilitat d'adaptació, escolta activa, proactivitat, empatia, respecte i tolerància.",
  "lg.ru": "Rus",
  "lg.ru.n": "Llengua materna",
  "lg.es": "Castellà",
  "lg.es.n": "C1",
  "lg.ca": "Català",
  "lg.ca.n": "C1",
  "lg.en": "Anglès",
  "lg.en.n": "B1-B2",

  "contact.h": "Contacte",
  "contact.claim": "Parlem-ne",
  "contact.intro": "Si et quadra el meu perfil, escriu-me per on et vagi millor. Contesto de seguida.",
  "contact.mail": "Correu",
  "contact.li": "El perfil sencer, amb més detall",
  "contact.gh": "Tot el codi dels projectes",
  "foot.made": "Fet a mà amb React i TypeScript",

  "porta.eyebrow": "Portafoli",
  "porta.titular": "Tècnic IT · Sistemes · Ciberseguretat",
  "porta.user": "Usuari",
  "porta.pass": "Contrasenya",
  "porta.nota": "Entra com a convidat, ja ho tens tot posat.",
  "porta.enter": "Entrar",
  "porta.sending": "Entrant",
  "porta.retry": "Tornar-ho a provar",
  "porta.checking": "Comprovant la sessió desada.",
  "porta.slow": "El servidor estava adormit i s'està engegant. Prop d'un minut és el normal.",
  "porta.err.empty": "Escriu l'usuari i la contrasenya.",
  "porta.err.creds": "L'usuari o la contrasenya no quadren.",
  "porta.err.net": "No s'ha pogut contactar amb el servidor. Mira la connexió i torna-ho a provar.",
  "porta.err.time": "El servidor no ha contestat a temps. Torna-ho a provar.",
  "porta.err.server": "El servidor ha contestat amb un error. Prova-ho un altre cop d'aquí a un moment."
};

const en: Partial<Record<Clau, string>> = {
  "skip": "Skip to content",
  "nav.aria": "Sections",
  "nav.about": "About me",
  "nav.projects": "Projects",
  "nav.edu": "Education",
  "nav.skills": "Skills",
  "nav.contact": "Contact",
  "lang.aria": "Language",
  "sortir": "Sign out",
  "doc.title": "Alex Aiguadé Alisultánov · Portfolio",

  "hero.eyebrow": "IT technician · Systems · Cybersecurity",
  "hero.lead": "IT technician focused on systems and cybersecurity, with a background in application development. I'm taking the Master's in Cybersecurity and AI right now. I'm looking to join the IT department of a company in the field.",
  "hero.cta": "See the projects",
  "hero.alt": "Portrait of Alex Aiguadé Alisultánov",
  "hero.d1k": "Right now",
  "hero.d1v": "Master's in Cybersecurity and AI",
  "hero.d1n": "Evolve, in progress",
  "hero.d2k": "Base",
  "hero.d2v": "Application Development",
  "hero.d2n": "Advanced vocational, 2024",
  "hero.d3k": "Published projects",
  "hero.d3n": "Open source on GitHub",
  "hero.d4k": "Where",
  "hero.d4v": "Anglesola, Catalonia",
  "hero.d4n": "Spain",

  "about.h": "About me",
  "about.claim": "I protect what I first learned to build.",
  "about.p1": "I'm a Higher Technician in Application Development and I'm currently taking the Master's in Cybersecurity and Artificial Intelligence at Evolve. My base is programming; what I work on now is protecting digital assets and using AI to make processes safer and leaner.",
  "about.p2": "I'm looking to join the IT department of a company in the cybersecurity field, where I can contribute to infrastructure management, task automation and building secure solutions. My English is intermediate (B1-B2), enough to work inside a technical team.",
  "about.p3": "What interests me most: developing and integrating secure software, hands-on cybersecurity and IT systems management, AI applied to technical environments, and automating whatever repeats. The projects below are web development, from my vocational training years, and they still say how I work.",

  "proj.h": "Projects",
  "proj.intro": "Each card lists the technologies behind the project and, once it is deployed, the link to try it.",
  "proj.code": "Code on GitHub",
  "chips.aria": "Technologies",
  "chip.qr": "QR codes",
  "chip.equip": "Team project",
  "obres.nom": "Under construction",
  "obres.why": "This one is still halfway there. Better not to peek under the tarp until it is finished.",
  "feed.loading": "Reading the repositories from GitHub",
  "feed.cache": "GitHub is not answering right now, so this is the last list that was saved.",
  "feed.offline": "GitHub is not answering right now, so this is the usual list, without the date of each repository.",
  "feed.nodesc": "No description on GitHub yet. The code is published and you can go through it.",
  "feed.updated": "Updated {t}",
  "feed.try": "Try the app",
  "feed.code": "Code",
  "feed.soon": "Demo on the way",
  "feed.onlycode": "Code only for now",

  "wake.title": "The demos fall asleep on their own",
  "wake.text": "They run on a free plan that shuts them down after fifteen minutes without visits. Start them all at once, or one at a time from its card, and each one tells you how it is doing. From here all you can know is whether the server answers, not what it answers.",
  "wake.on": "Start the {n} demos",
  "wake.on.one": "Start the demo",
  "wake.working": "{n} still to answer",
  "wake.working.one": "1 still to answer",
  "wake.retry": "Try {n} again",
  "wake.retry.one": "Try it again",
  "wake.done": "The demos are up",
  "wake.hint": "The first start takes close to a minute. You can keep reading meanwhile.",
  "wake.hint.working": "Close to a minute is normal. {s} s so far.",
  "wake.hint.done": "They stay up while you use them. After fifteen minutes without visits they go back to sleep.",
  "wake.hint.some": "One of them did not answer in time. You can try again from its card or from here.",
  "wake.live.on": "Starting {n} demos. It can take close to a minute.",
  "wake.live.on.one": "Starting one demo. It can take close to a minute.",
  "wake.live.ready": "{t}: answering now, you can open it.",
  "wake.live.fail": "{t}: no answer.",
  "wake.live.done": "Every demo answers.",
  "wake.live.starting": "{t}: starting up. It can take close to a minute.",
  "demo.start": "Start the demo",
  "estat.off": "Not checked",
  "estat.off.why": "Start it to be able to open it.",
  "estat.waking": "Starting up",
  "estat.waking.why": "The server is starting up. It usually takes close to a minute.",
  "estat.on": "Up",
  "estat.on.why": "It answers, you can open it.",
  "estat.fail": "No answer",
  "estat.fail.why": "Two and a half minutes went by with no answer. Give it another go.",
  "estat.secs": "{s} s",
  "estat.again": "Try again",

  "edu.h": "Education",
  "edu.intro": "Where the development base and the security specialisation come from.",
  "edu.aria": "Contents",
  "edu.ev.when": "April 2026 to December 2026",
  "edu.ev.tag": "In progress",
  "edu.ev.title": "Master's in Cybersecurity and Artificial Intelligence",
  "edu.ev.c1": "Ethical hacking and audit methodology",
  "edu.ev.c2": "Passive and active reconnaissance",
  "edu.ev.c3": "OSINT and footprinting",
  "edu.ev.c4": "Network protocols, segmentation and communication architectures",
  "edu.ev.c5": "Vulnerability exploitation",
  "edu.ev.c7": "Pivoting, lateral movement and privilege escalation",
  "edu.ev.c8": "Regulation, compliance and the legal framework",
  "edu.ev.c9": "Advanced pentesting in real environments",
  "edu.ev.c11": "Blue Team, SOC and incident response",
  "edu.ls.when": "September 2022 to May 2024",
  "edu.ls.title": "Advanced vocational training in Application Development",
  "edu.ls.note": "Average grade 6.313",
  "edu.gm.when": "2020 to 2022",
  "edu.gm.title": "Intermediate vocational training in Microcomputer Systems and Networks",

  "skills.h": "Skills",
  "skills.intro": "Grouped by family, so you can tell at a glance what each part is about.",
  "skills.g1": "Pentesting and offensive security",
  "skills.g2": "Defence",
  "skills.g3": "Methodologies and regulation",
  "skills.g4": "Programming and data",
  "skills.g5": "Artificial intelligence",
  "skills.g6": "Personal skills",
  "skills.g7": "Languages",
  "sk.explo": "Vulnerability exploitation",
  "sk.esc": "Privilege escalation",
  "sk.lat": "Lateral movement and pivoting",
  "sk.post": "Post-exploitation",
  "sk.wifi": "Wi-Fi and mobile auditing",
  "sk.e2e": "End-to-end audits",
  "sk.info": "Executive reporting",
  "sk.inc": "Incident response",
  "sk.cve": "CVE and NVD",
  "sk.rgpd": "GDPR",
  "sk.ag": "Agents with Python",
  "sk.ml": "Machine learning",
  "sk.llm": "Language models",
  "sk.iacyber": "AI applied to cybersecurity",
  "skills.soft": "From my years at La Salle Mollerussa: teamwork, problem solving, responsibility, easy adaptation, active listening, initiative, empathy, respect and tolerance.",
  "lg.ru": "Russian",
  "lg.ru.n": "Mother tongue",
  "lg.es": "Spanish",
  "lg.es.n": "C1",
  "lg.ca": "Catalan",
  "lg.ca.n": "C1",
  "lg.en": "English",
  "lg.en.n": "B1-B2",

  "contact.h": "Contact",
  "contact.claim": "Let's talk",
  "contact.intro": "If my profile fits what you need, write to me wherever suits you best. I answer quickly.",
  "contact.mail": "Email",
  "contact.li": "The full profile, in more detail",
  "contact.gh": "All the code from the projects",
  "foot.made": "Handmade with React and TypeScript",

  "porta.eyebrow": "Portfolio",
  "porta.titular": "IT technician · Systems · Cybersecurity",
  "porta.user": "Username",
  "porta.pass": "Password",
  "porta.nota": "Come in as a guest, everything is already filled in.",
  "porta.enter": "Sign in",
  "porta.sending": "Signing in",
  "porta.retry": "Try again",
  "porta.checking": "Checking the saved session.",
  "porta.slow": "The server was asleep and is starting up. Close to a minute is normal.",
  "porta.err.empty": "Type the username and the password.",
  "porta.err.creds": "That username and password do not match.",
  "porta.err.net": "Could not reach the server. Check your connection and try again.",
  "porta.err.time": "The server did not answer in time. Try again.",
  "porta.err.server": "The server answered with an error. Give it another go in a moment."
};

const DICCIONARIS: Record<Idioma, Partial<Record<Clau, string>>> = { es, ca, en };

/** Texto en el idioma pedido. Si falta una frase se cae al castellano, nunca a la clave. */
export function traduir(idioma: Idioma, clau: Clau): string {
  return DICCIONARIS[idioma][clau] ?? es[clau] ?? "";
}

type Context = {
  idioma: Idioma;
  t: (clau: Clau, valors?: Record<string, string | number>) => string;
  canviar: (idioma: Idioma) => void;
};

const IdiomaContext = createContext<Context | null>(null);

function recordat(): Idioma {
  try {
    const desat = window.localStorage.getItem(CLAU);
    if (desat === "ca" || desat === "en" || desat === "es") return desat;
  } catch {
    // Ventana privada o almacenamiento bloqueado: se arranca en castellano.
  }
  return "es";
}

export function ProveidorIdioma({ children }: { children: ReactNode }) {
  const [idioma, setIdioma] = useState<Idioma>(recordat);

  useEffect(() => {
    document.documentElement.lang = idioma;
    document.title = traduir(idioma, "doc.title");
  }, [idioma]);

  const canviar = useCallback((nou: Idioma) => {
    setIdioma(nou);
    try {
      window.localStorage.setItem(CLAU, nou);
    } catch {
      // La eleccion dura lo que la visita.
    }
  }, []);

  const t = useCallback(
    (clau: Clau, valors?: Record<string, string | number>) => {
      let text = traduir(idioma, clau);
      if (valors) {
        for (const nom of Object.keys(valors)) {
          text = text.split("{" + nom + "}").join(String(valors[nom]));
        }
      }
      return text;
    },
    [idioma]
  );

  const valor = useMemo(() => ({ idioma, t, canviar }), [idioma, t, canviar]);
  return <IdiomaContext value={valor}>{children}</IdiomaContext>;
}

export function useIdioma(): Context {
  const valor = useContext(IdiomaContext);
  if (!valor) throw new Error("useIdioma necesita estar dentro de ProveidorIdioma");
  return valor;
}
